### ISSUE TITLE
references are added, even when commented out

### ISSUE THREAD

**Issue by bjdmeest** [rubensworks/ScholarMarkdown#11]
eg

```
Text citing [a](cite:cites a).

<!--
Commented text citing [b](cite:cites b).
-->
```

Will result in a reference list of **2**.
The actual issue is https://github.com/RubenVerborgh/BibMarkdown/issues/5 , 
However, maybe add a comment int the wiki?

**Comment by rubensworks** [comment]
The reason for this is that the references are processed _before_ the kramdown, so the comments are still present in this step.

What we could do is simply add a comment-removal phase before the processing of references.

@RubenVerborgh Do you agree? Or do you think handling this in BibMarkdown would be easier?

**Comment by RubenVerborgh** [comment]
BibMarkdown should probably do this.

**Comment by rubensworks** [comment]
Ok, closing this here then.
