### ISSUE TITLE
Bug ACM styling

### ISSUE THREAD

**Issue by brechtvdv** [rubensworks/ScholarMarkdown#15]
I tried to add ACM styling by referencing it in print.scss:
https://github.com/brechtvdv/Article-Rich-Snippets/blob/master/content/styles/print.scss

I also added the sass file here:
https://github.com/brechtvdv/Article-Rich-Snippets/blob/master/content/styles/acm.scss

Still, the print output is lncs

**Comment by rubensworks** [comment]
Fixed it in your repo, some CSS changes were required.

I'll document this here too.

**Comment by rubensworks** [comment]
As of 21c61481e1d0100a2575114a972ac74b463f9358, the generator can now initialize ACM articles as well by running `generate-scholarmarkdown my-awesome-article acm`
