### ISSUE TITLE
strikethrough does not work :(

### ISSUE THREAD

**Issue by andimou** [rubensworks/ScholarMarkdown#19]
Even if I copy-paste the example from the wiki:

`<strikethrough>This is a comment about the text. (RT)</strikethrough>`

nothing happens, the text appears without any strike.h

**Comment by rubensworks** [comment]
You should use something like:
```
<del class="comment" data-author="RT">
This is something that must be deleted.
</del>
```

(you were probably looking at the output at https://github.com/rubensworks/ScholarMarkdown/wiki/Snippets)

Also, `<strikethrough>` is not a valid tag, but `<strike>` is, which you can also use (also fixed in the wiki now).

**Comment by andimou** [comment]
yes I was looking at the snippets.

Indeed `<strike>` works, thanks for the quick reply!
