### ISSUE TITLE
Exclude therubyracer dependency for Win platforms

### ISSUE THREAD

**Issue by simonstey** [rubensworks/ScholarMarkdown#22]
https://github.com/rubensworks/ScholarMarkdown/blob/6aae44febbae9f896d79293469341a9fe4e169e4/Gemfile#L16

if the only reason for including this gem is to get v8 support, please consider adding `:platforms => :ruby` to exclude this gem from being installed on Windows machines. I wasn't able to install ScholarMarkdown until I manually excluded its `therubyracer` dependency and built ScholarMarkdown locally.

**Comment by rubensworks** [comment]
Sure, I can easily add that.
But I guess this means that V8 (and the math-mode feature of ScholarMarkdown) will not work on Windows anymore, which is not an ideal solution.

**Comment by simonstey** [comment]
> But I guess this means that V8 (and the math-mode feature of ScholarMarkdown) will not work on Windows anymore, which is not an ideal solution.

no, but Windows comes with its own JS runtime -> https://stackoverflow.com/a/6359265 :)

**Comment by rubensworks** [comment]
Ah, that's good to know.
@joachimvh will be happy to hear this as well :-)
