### ISSUE TITLE
[BUG] Numbering not working in Safari when printing

### ISSUE THREAD

**Issue by thepieterdc** [rubensworks/ScholarMarkdown#26]
It appears that numbering is not working in Safari. An example from your example paper: https://rdfostrich.github.io/article-mocha-2018/

[Versioned Querying with OSTRICH and Comunica in MOCHA 2018.pdf](https://github.com/rubensworks/ScholarMarkdown/files/5612637/Versioned.Querying.with.OSTRICH.and.Comunica.in.MOCHA.2018.pdf)

<img width="626" alt="image" src="https://user-images.githubusercontent.com/6131398/100550509-b80a1700-327a-11eb-8702-7245b91c738f.png">

**Comment by rubensworks** [comment]
Weird, it's working fine on my end though (Safari, Chrome and Firefox).
My Safari version is 13.1 (15609.1.20.111.8).

Are you by any chance running on Safari 14 for Big Sur? Since it's quite new, there _may_ be some bugs in its CSS engine still.

**Comment by thepieterdc** [comment]
@rubensworks I am indeed running Safari 14, however on Catalina. It seems like a Safari issue indeed then.

**Comment by rubensworks** [comment]
Ok, thanks for checking. Putting this issue on hold for now.

**Comment by rubensworks** [comment]
I haven't seen this issue anymore, so I consider this resolved.
