### ISSUE TITLE
Are there default GitHub CI actions we can use to publish the result automatically?

### ISSUE THREAD

**Issue by RubenVerborgh** [rubensworks/ScholarMarkdown#28]

**Comment by rubensworks** [comment]
Yes, the following workflow can be reused: https://github.com/rubensworks/ScholarMarkdown/wiki/Self-publishing#github-actions

No editing is necessary, just a full copy-paste will work.

**Comment by RubenVerborgh** [comment]
Thanks, I had missed the readme link!

**Comment by RubenVerborgh** [comment]
I had to change

```
          ruby-version: '3.0'
```

(note the quotes—otherwise it parses to 3 and hence `3.x`).

and `bundle lock --add-platform x86_64-linux` from my Mac.
