### ISSUE TITLE
notifu needed on Windows

### ISSUE THREAD

**Issue by bjdmeest** [rubensworks/ScholarMarkdown#3]
I had to add `gem 'rb-notifu' if Gem.win_platform?` to the development part of Gemfile to have the live-reload working on windows.
My development then looked like this:

```
group :development do
  # live view
  gem 'guard-nanoc', '~> 2.1.2'
  gem 'guard-process'
  gem 'guard-livereload'
  gem 'serve'
  gem 'thin'
  gem 'rack-livereload'
  gem 'wdm', '>= 0.1.0' if Gem.win_platform?
  gem 'rb-readline'
  gem 'rb-notifu' if Gem.win_platform?
end
```

**Comment by rubensworks** [comment]
Ah, thanks for letting me know, I'll look into adding it here as well!

@joachimvh Did you have to include something like this as well?

**Comment by joachimvh** [comment]
I don't think I ever used live-reload (possibly because it didn't work, probably because of this :D)
