### ISSUE TITLE
Add CSS class snippets to wiki

### ISSUE THREAD

**Issue by bjdmeest** [rubensworks/ScholarMarkdown#5]
For myself, I'd think it would have been much easier to start with this if following snippets would have been included in https://github.com/rubensworks/ScholarMarkdown/wiki/Snippets

## Using Custom visualizations: Kramdown

The default CSS (check `shared.css`) includes some custom visualization classes, useful for writing, such as marking TODO's, comments, and reviewing statements (spelling, grammar, rephrase, reference needed).
As ScholarMarkdown supports Kramdown, you can add attributes via curly bracket notation (`{:[options]}`), so we can use these classes as follows:

for [inline](https://kramdown.gettalong.org/quickref.html#inline-attributes), the curly brackets need to come after an inline element (such as italic):

```
This is a paragraph.
_This sentence are badly grammared_{:.grammar}.
The evaluation shows that we are better in _X%_{:.todo} of the cases*.*{:.reference.needed}.
```

This will render as 

```
<p>This is a paragraph.
<em class="grammar">This sentence are badly grammared</em>.
The evaluation shows that we are better in <em class="todo">X%</em> of the cases<em class="reference needed">.</em>.</p>
```

for [block-level elements](https://kramdown.gettalong.org/quickref.html#block-attributes), the curly brackets need to come after a block-level element (such as a paragraph or blockquote):

```
This paragraph is done.

>{:.todo}
This blockquote needs some work

{:.todo}
This paragraph also isn't finished

```

This will render as 

```
<p>This paragraph is done.</p>

<blockquote>
  <p class="todo">This blockquote needs some work</p>
</blockquote>

<p class="todo">This paragraph also isn’t finished</p>
```

**Comment by rubensworks** [comment]
Yes, the wiki can definitely be improved :-)

I'll try to incorporate your suggestion.

Or perhaps it might even be better to just include this as part of the quick-start guide...

**Comment by bjdmeest** [comment]
Ideally, I would like to see it in the initial generated content, and in the wiki :)

**Comment by rubensworks** [comment]
Updated the wiki based on your suggestion, thanks for the input!
