### ISSUE TITLE
How can you add a footnote?

### ISSUE THREAD

**Issue by bjdmeest** [rubensworks/ScholarMarkdown#6]
I see there are CSS-statements, but I cannot find an example

**Comment by rubensworks** [comment]
Here's an example: https://github.com/LinkedSoftwareDependencies/Article-Reproducability/commit/504cb6cf29772abbb310d43d8a7a69b555b5604c

(Will add it to documentation later, as that's quite important indeed)

**Comment by rubensworks** [comment]
Added to the wiki: https://github.com/rubensworks/ScholarMarkdown/wiki/Snippets#footnotes
