### ISSUE TITLE
Decouple inbox/annotation config from dokieli

### ISSUE THREAD

**Issue by csarven** [rubensworks/ScholarMarkdown#7]
If an article can announce its inbox and/or annotation, that should be possible without having dokieli involved in the config. A client application can consume the document and use whatever affordances there are.

**Comment by rubensworks** [comment]
Not sure what would be the best way to go here.
In my first implementation I had them (dokieli + inbox/annotation) decoupled, but I ended up merging them as I assume most people would use both of them anyways.

So there are two options:
1. Decouple them: function to include inbox/annotation + config option to add dokieli script
2. Make the inbox/annotation params for the dokieli config optional, and make a separate function to include inbox/annotation in cases when dokieli is not needed.

The first option is a bit cleaner, with better separation of concerns. But the second option might be more user-friendly for users that are not really concerned with what happens on the back-end.
Currently the first option has my preference, but I'll think about it a bit.

**Comment by csarven** [comment]
Consider potential reuse just to be pragmatic. Decouple the config so that people can reuse ScholarMarkdown without feeling like they have to commit to dokieli. inbox/annotation do their own thing, and so similarly, there is no expectation that a server needs to be installed at the same time when inbox/annotation is on.

So, I totally ack the reason to be user-friendly, but it is just a config away. You could even ship the default config to have dokieli "on", but at least allow it to be replaced by something else. Perhaps a config like: `client-ui: "https://dokie.li/"` and I suppose you'd simply check the client-ui value and import/include dokieli's CSS/JS. Alternative client-side UI would introduce their own package with the same config.
